spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://localhost:5432/card_service_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
